USE [master]
GO

/****** Object:  Database [northwind_dw]    Script Date: 6/8/2024 2:05:19 PM ******/
CREATE DATABASE [northwind_dw]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'northwind_dw', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\northwind_dw.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'northwind_dw_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\northwind_dw_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [northwind_dw].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [northwind_dw] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [northwind_dw] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [northwind_dw] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [northwind_dw] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [northwind_dw] SET ARITHABORT OFF 
GO

ALTER DATABASE [northwind_dw] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [northwind_dw] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [northwind_dw] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [northwind_dw] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [northwind_dw] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [northwind_dw] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [northwind_dw] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [northwind_dw] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [northwind_dw] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [northwind_dw] SET  ENABLE_BROKER 
GO

ALTER DATABASE [northwind_dw] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [northwind_dw] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [northwind_dw] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [northwind_dw] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [northwind_dw] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [northwind_dw] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [northwind_dw] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [northwind_dw] SET RECOVERY FULL 
GO

ALTER DATABASE [northwind_dw] SET  MULTI_USER 
GO

ALTER DATABASE [northwind_dw] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [northwind_dw] SET DB_CHAINING OFF 
GO

ALTER DATABASE [northwind_dw] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [northwind_dw] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [northwind_dw] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [northwind_dw] SET QUERY_STORE = OFF
GO

USE [northwind_dw]
GO

EXEC [northwind_dw].sys.sp_addextendedproperty @name=N'Description', @value=N'Default description - you should change this.' 
GO

USE [master]
GO

ALTER DATABASE [northwind_dw] SET  READ_WRITE 
GO

